import { pgTable, uuid, text, timestamp, jsonb, integer, boolean, index } from 'drizzle-orm/pg-core';
import { clients } from './clients.js';
import { icps } from './icps.js';

export const personas = pgTable('personas', {
  id: uuid('id').primaryKey().defaultRandom(),
  clientId: uuid('client_id').notNull().references(() => clients.id, { onDelete: 'cascade' }),
  icpId: uuid('icp_id').notNull().references(() => icps.id, { onDelete: 'cascade' }),

  name: text('name').notNull(),
  description: text('description'),

  titlePatterns: jsonb('title_patterns').$type<string[]>().notNull().default([]),
  seniorityLevels: jsonb('seniority_levels').$type<string[]>().notNull().default([]),
  departments: jsonb('departments').$type<string[]>().notNull().default([]),

  countries: jsonb('countries').$type<string[]>().default([]),
  states: jsonb('states').$type<string[]>().default([]),

  yearsExperienceMin: integer('years_experience_min'),
  yearsExperienceMax: integer('years_experience_max'),
  excludeTitlePatterns: jsonb('exclude_title_patterns').$type<string[]>().default([]),

  isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
  generatedFromIcpId: uuid('generated_from_icp_id'),

  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_personas_client').on(table.clientId),
  index('idx_personas_icp').on(table.icpId),
]);
